//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificacion_de_servicio
    {
        public int ID_calificacion { get; set; }
        public byte nivel_de_calificacion { get; set; }
        public string comentario { get; set; }
        public int ID_servicio { get; set; }
    
        public virtual Servicio Servicio { get; set; }
    }
}
