//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servicio()
        {
            this.Calificacion_de_servicio = new HashSet<Calificacion_de_servicio>();
            this.Producto_por_servicio = new HashSet<Producto_por_servicio>();
        }
    
        public int ID_servicio { get; set; }
        public System.DateTime fecha_del_servicio { get; set; }
        public int numero_de_horas { get; set; }
        public System.TimeSpan hora_de_inicio { get; set; }
        public Nullable<System.TimeSpan> hora_de_fin { get; set; }
        public double comision_empresa { get; set; }
        public Nullable<int> pago_a_trabajador { get; set; }
        public Nullable<double> precio_de_servicio { get; set; }
        public int ID_solicitud { get; set; }
        public int ID_direccion { get; set; }
        public int ID_trabajador { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calificacion_de_servicio> Calificacion_de_servicio { get; set; }
        public virtual Direccion Direccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto_por_servicio> Producto_por_servicio { get; set; }
        public virtual Solicitud Solicitud { get; set; }
        public virtual Trabajador Trabajador { get; set; }
    }
}
