//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Servicios_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Servicios_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\ignac\AppData\Local\Temp\7CB30C5F95E2F5A600E8192A84D39C717EF9\2\web_CleanServe\web_CleanServe\Views\Home\Servicios.cshtml"
  
    ViewBag.Title = "Servicios";


#line default
#line hidden

#line 2 "C:\Users\ignac\AppData\Local\Temp\7CB30C5F95E2F5A600E8192A84D39C717EF9\2\web_CleanServe\web_CleanServe\Views\Home\Servicios.cshtml"
            foreach (var item in ViewBag.Calificaciones)
            {
                

#line default
#line hidden

#line 3 "C:\Users\ignac\AppData\Local\Temp\7CB30C5F95E2F5A600E8192A84D39C717EF9\2\web_CleanServe\web_CleanServe\Views\Home\Servicios.cshtml"
                   __o = item.ID_calificacion;


#line default
#line hidden

#line 4 "C:\Users\ignac\AppData\Local\Temp\7CB30C5F95E2F5A600E8192A84D39C717EF9\2\web_CleanServe\web_CleanServe\Views\Home\Servicios.cshtml"
                        for (int i = 0; i < item.nivel_de_calificacion; i++)
                        {
                            

#line default
#line hidden

#line 5 "C:\Users\ignac\AppData\Local\Temp\7CB30C5F95E2F5A600E8192A84D39C717EF9\2\web_CleanServe\web_CleanServe\Views\Home\Servicios.cshtml"
                                                                      
                        }

#line default
#line hidden

#line 6 "C:\Users\ignac\AppData\Local\Temp\7CB30C5F95E2F5A600E8192A84D39C717EF9\2\web_CleanServe\web_CleanServe\Views\Home\Servicios.cshtml"
                   __o = item.comentario;


#line default
#line hidden

#line 7 "C:\Users\ignac\AppData\Local\Temp\7CB30C5F95E2F5A600E8192A84D39C717EF9\2\web_CleanServe\web_CleanServe\Views\Home\Servicios.cshtml"
                   __o = item.ID_servicio;


#line default
#line hidden

#line 8 "C:\Users\ignac\AppData\Local\Temp\7CB30C5F95E2F5A600E8192A84D39C717EF9\2\web_CleanServe\web_CleanServe\Views\Home\Servicios.cshtml"
                     
            }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Servicios_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Servicios_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\ignac\AppData\Local\Temp\A1BFA18CF6E5913FAE5D7B68E14BCA620BBF\4\web_CleanServe\web_CleanServe\Views\Home\Servicios.cshtml"
  
    ViewBag.Title = "Servicios";


#line default
#line hidden

#line 2 "C:\Users\ignac\AppData\Local\Temp\A1BFA18CF6E5913FAE5D7B68E14BCA620BBF\4\web_CleanServe\web_CleanServe\Views\Home\Servicios.cshtml"
            foreach (var item in ViewBag.Calificaciones)
            {
                

#line default
#line hidden

#line 3 "C:\Users\ignac\AppData\Local\Temp\A1BFA18CF6E5913FAE5D7B68E14BCA620BBF\4\web_CleanServe\web_CleanServe\Views\Home\Servicios.cshtml"
                   __o = item.ID_calificacion;


#line default
#line hidden

#line 4 "C:\Users\ignac\AppData\Local\Temp\A1BFA18CF6E5913FAE5D7B68E14BCA620BBF\4\web_CleanServe\web_CleanServe\Views\Home\Servicios.cshtml"
                        for (int i = 0; i < item.nivel_de_calificacion; i++)
                        {
                            

#line default
#line hidden

#line 5 "C:\Users\ignac\AppData\Local\Temp\A1BFA18CF6E5913FAE5D7B68E14BCA620BBF\4\web_CleanServe\web_CleanServe\Views\Home\Servicios.cshtml"
                                                                      
                        }

#line default
#line hidden

#line 6 "C:\Users\ignac\AppData\Local\Temp\A1BFA18CF6E5913FAE5D7B68E14BCA620BBF\4\web_CleanServe\web_CleanServe\Views\Home\Servicios.cshtml"
                   __o = item.comentario;


#line default
#line hidden

#line 7 "C:\Users\ignac\AppData\Local\Temp\A1BFA18CF6E5913FAE5D7B68E14BCA620BBF\4\web_CleanServe\web_CleanServe\Views\Home\Servicios.cshtml"
                   __o = item.ID_servicio;


#line default
#line hidden

#line 8 "C:\Users\ignac\AppData\Local\Temp\A1BFA18CF6E5913FAE5D7B68E14BCA620BBF\4\web_CleanServe\web_CleanServe\Views\Home\Servicios.cshtml"
                     
            }

#line default
#line hidden
}
}
}
